#
# GRAKN.AI - THE KNOWLEDGE GRAPH
# Copyright (C) 2019 Grakn Labs Ltd
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

version: 2.1
commands:
  install-bazel-linux-rbe:
    steps:
      - run: curl -OL https://raw.githubusercontent.com/graknlabs/build-tools/master/ci/install-bazel-linux.sh
      - run: bash ./install-bazel-linux.sh && rm ./install-bazel-linux.sh
      - run: curl -OL https://raw.githubusercontent.com/graknlabs/build-tools/master/ci/install-bazel-rbe.sh
      - run: bash ./install-bazel-rbe.sh && rm ./install-bazel-rbe.sh

  run-bazel-rbe:
    parameters:
      command:
        type: string
    steps:
      - run: bazel run @graknlabs_build_tools//ci:run-bazel-rbe -- << parameters.command >>

  run-grakn-server:
    steps:
      - run-bazel-rbe:
          command: bazel build @graknlabs_grakn_core//:assemble-linux-targz
      - run: mkdir dist && tar -xvzf bazel-genfiles/external/graknlabs_grakn_core/grakn-core-all-linux.tar.gz -C ./dist/
      - run: nohup ./dist/grakn-core-all-linux/grakn server start

jobs:
  build:
    machine: true
    working_directory: ~/client-python
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run-bazel-rbe:
          command: bazel build //...

  test:
    machine: true
    working_directory: ~/client-python
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: pyenv global 2.7.12 3.5.2
      - run-bazel-rbe:
          command: bazel test //:test_integration --test_output=streamed

  deploy-pip-snapshot:
    machine: true
    working_directory: ~/client-python
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: |
          echo -n "$(cat VERSION)-$CIRCLE_SHA1" > VERSION
          export DEPLOY_PIP_USERNAME=$REPO_GRAKN_USERNAME
          export DEPLOY_PIP_PASSWORD=$REPO_GRAKN_PASSWORD
          bazel run //:deploy-pip -- snapshot

  test-deployment:
    machine: true
    working_directory: ~/client-python
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install python-pip
      - run-grakn-server
      - run:
          name: Run test-deployment for client-python
          command: |
            echo -n "$(cat VERSION)-$CIRCLE_SHA1" > VERSION
            sed -i -e "s/CLIENT_PYTHON_VERSION_MARKER/$(cat VERSION)/g" tests/deployment/requirements.txt
            cat tests/deployment/requirements.txt
            pip install -r tests/deployment/requirements.txt
            cd tests/deployment/ && python -m unittest test

  sync-dependencies-snapshot:
    machine: true
    working_directory: ~/client-python
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: |
          export SYNC_DEPENDENCIES_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @graknlabs_build_tools//ci:sync-dependencies -- \
          --source client-python@$CIRCLE_SHA1 \
          --targets grakn-kgms:master docs:master examples:master kglib:master

  release-approval:
    machine: true
    working_directory: ~/client-python
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: |
          export RELEASE_APPROVAL_USERNAME=$REPO_GITHUB_USERNAME
          export RELEASE_APPROVAL_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @graknlabs_build_tools//ci:release-approval

  release-validate:
    machine: true
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: |
          bazel run @graknlabs_build_tools//ci:release-validate-deps -- \
            graknlabs_protocol

  deploy-github:
    machine: true
    working_directory: ~/client-python
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: |
          pip install certifi
          export RELEASE_NOTES_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @graknlabs_build_tools//ci:release-notes -- client-python $(cat VERSION) ./RELEASE_TEMPLATE.md
      - run: |
          export DEPLOY_GITHUB_TOKEN=$REPO_GITHUB_TOKEN
          bazel run //:deploy-github -- $CIRCLE_SHA1

  deploy-pip-release:
    machine: true
    working_directory: ~/client-python
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: |
          export DEPLOY_PIP_USERNAME=$REPO_PYPI_USERNAME
          export DEPLOY_PIP_PASSWORD=$REPO_PYPI_PASSWORD
          bazel run //:deploy-pip -- release

  sync-dependencies-release:
    machine: true
    working_directory: ~/client-python
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: |
          export SYNC_DEPENDENCIES_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @graknlabs_build_tools//ci:sync-dependencies -- \
          --source client-python@$(cat VERSION) \
          --targets grakn-kgms:master docs:master examples:master kglib:master

  release-cleanup:
    machine: true
    steps:
      - checkout
      - run: git push --delete https://$REPO_GITHUB_TOKEN@github.com/graknlabs/client-python $CIRCLE_BRANCH

workflows:
  client-python:
    jobs:
      - build:
          filters:
            branches:
              ignore: client-python-release-branch
      - test:
          filters:
            branches:
              ignore: client-python-release-branch
      - deploy-pip-snapshot:
          filters:
            branches:
              only: master
          requires:
            - build
            - test
      - test-deployment:
          filters:
            branches:
              only: master
          requires:
            - deploy-pip-snapshot
      - sync-dependencies-snapshot:
          filters:
            branches:
              only: master
          requires:
            - test-deployment
      - release-approval:
          filters:
            branches:
              only: master
          requires:
            - sync-dependencies-snapshot

  client-python-release:
    jobs:
      - release-validate:
          filters:
            branches:
              only: client-python-release-branch
      - deploy-github:
          filters:
            branches:
              only: client-python-release-branch
          requires:
            - release-validate
      - deploy-approval:
          type: approval
          filters:
            branches:
              only: client-python-release-branch
          requires:
            - deploy-github
      - deploy-pip-release:
          filters:
            branches:
              only: client-python-release-branch
          requires:
            - deploy-approval
      - sync-dependencies-release:
          filters:
            branches:
              only: client-python-release-branch
          requires:
            - deploy-pip-release
      - release-cleanup:
          filters:
            branches:
              only: client-python-release-branch
          requires:
            - sync-dependencies-release
